# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
<<<<<<< HEAD
image: node:latest
=======
image: kkarczmarczyk/node-yarn:latest
>>>>>>> 9c2a6eed2d0be7a58596ad2f5e62b11e5ff68552

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
<<<<<<< HEAD
  - node_modules/

test_async:
  script:
   - node --version
   - npm --version
   - npm install --global yarn --verbose
   - yarn install
   - yarn test
=======
    - node_modules/

# Install dependencies.
before_script:
  - yarn install

# Run test.
test:
  script:
    - yarn test
>>>>>>> 9c2a6eed2d0be7a58596ad2f5e62b11e5ff68552
