import * as actionType from 'type/textfield'

export const USERNAME_TEXTFIELD_VALUE_CHANGE = 'USERNAME_TEXTFIELD_VALUE_CHANGE'
export const PASSWORD_TEXTFIELD_VALUE_CHANGE = 'PASSWORD_TEXTFIELD_VALUE_CHANGE'
